include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    avoid_annotating_with_dynamic: error

  exclude:
    - "*.g.dart"

formatter:
  page_width: 80

linter:
  rules:
    - prefer_single_quotes
    - avoid_redundant_argument_values
    - always_use_package_imports
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_dynamic_calls
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_positional_boolean_parameters
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - close_sinks
    - deprecated_consistency
    - directives_ordering
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_const_declarations
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - strict_top_level_inference
    - tighten_type_of_initializing_formals
    - unnecessary_await_in_return
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
